### ISSUE TITLE
Fix exception in npm script eslint

### ISSUE THREAD

**Issue by Mitgenosse** [Mitgenosse/brain.dmp-frontend#1]
`
npm run eslint
`

throws an error after executing.

npm-debug.log
`
13 info lifecycle brain.dmp-frontend@0.0.1~eslint: Failed to exec eslint script  
14 verbose stack Error: brain.dmp-frontend@0.0.1 eslint: `eslint src/`  
14 verbose stack Exit status 1  
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifec
ycle.js:232:16)  
14 verbose stack     at emitTwo (events.js:87:13)  
14 verbose stack     at EventEmitter.emit (events.js:172:7)  
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn
.js:24:14)  
14 verbose stack     at emitTwo (events.js:87:13)  
14 verbose stack     at ChildProcess.emit (events.js:172:7)  
14 verbose stack     at maybeClose (internal/child_process.js:821:16)  
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_proc
ess.js:211:5)  
15 verbose pkgid brain.dmp-frontend@0.0.1  
`

**Comment by Mitgenosse** [comment]
Intended behaviour.
See: https://github.com/npm/npm/issues/8802
